services:
  payment:
    container_name:  payment
    build:
        context: ./payment
        args:
          JDK_VERSION: 17
        dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-network
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-network
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432


volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-network:
    name: spring_network