server.servlet.contextPath: /
server.port: 80

spring:
  application:
    name: TRANSACTION-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-payment:3306/test?useSSL=false
    username: testuser
    password: testuser@123
    hikari:
      initialization-fail-timeout: 0
  jpa:
      database-platform: org.hibernate.dialect.MySQL5Dialect
      generate-ddl: true
      show-sql: true
      hibernate:
        ddl-auto: update
        auto: update


# Open API
#springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.path: /


# management Actuator
management:
  endpoints:
    restart.enabled: true
    shutdown.enabled: true
  #management.endpoints.web.exposure.include=restart,health



#  Register Service on eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/