server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: PAYMENT-SERVICE
#                fallbackuri: forward:/userServiceFallBack
#        - id: DEPARTMENT-SERVICE
#          uri: lb://DEPARTMENT-SERVICE
#          predicates:
#            - Path=/departments/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: DEPARTMENT-SERVICE
#                fallbackuri: forward:/departmentServiceFallBack


#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000


#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream



#  Register Service on eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone:  http://service-registry:8761/eureka/
