server.servlet.contextPath: /
server.port: 8080

spring:
  application:
    name: PAYMENT-SERVICE


# Open API
#springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.path: /


# management Actuator
management:
  endpoints:
    restart.enabled: true
    shutdown.enabled: true
  #management.endpoints.web.exposure.include=restart,health



#  Register Service on eureka
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/