apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-app
  labels:
    app: client-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-service-app
  template:
    metadata:
      labels:
        app: client-service-app
    spec:
      containers:
        - name: client-service-app
          image: omerahmed41/client-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-svc
spec:
  ports:
    - targetPort: 9002
      port: 80
  selector:
    app: client-service-app
